name: fact-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - h5py=2.10.0
  - matplotlib=3.1.2
  - pip=19.3.1
  - numpy=1.17.3
  - python=3.7.6
  - pytorch=1.3.1
  - scipy=1.4.1
  - torchvision=0.4.2
  - pillow<7.0.0
  - pip:
    - torchsummary==1.5.1
